name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        # Frontend build and deploy
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20.9.0'

      # - name: Install frontend dependencies
      #   working-directory: ./frontend
      #   run: npm install

      # - name: Build frontend
      #   working-directory: ./frontend
      #   run: npm run build:prod

      # - name: Deploy frontend
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_PAGES_TOKEN_v2 }}
      #     publish_dir: ./frontend/dist/browser
      #     publish_branch: gh-pages
      #     cname: ${{ github.repository }}

        # Backend build and deploy
        

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant executable permissions to mvnw
        working-directory: ./backend
        run: chmod +x mvnw

      - name: Build backend
        working-directory: ./backend
        run: ./mvnw clean install package -DskipTests

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build \
            --build-arg DB_URL=${{ secrets.GH_PGSQL_URL }} \
            --build-arg DB_NAME=${{ secrets.GH_PGSQL_DB }} \
            --build-arg DB_USER=${{ secrets.GH_PGSQL_USER }} \
            --build-arg DB_PASSWORD=${{ secrets.GH_PGSQL_PASSWORD }} \
            --build-arg MAPBOX_API_KEY=${{ secrets.GH_MAPBOX_API_KEY }} \
            --build-arg SENDGRID_API_KEY=${{ secrets.GH_SENDGRID_API_KEY }} \
            --build-arg JWT_SECRET_KEY=${{ secrets.GH_JWT_SECRET_KEY }} \
            -t backend:latest .

          docker tag backend:latest ${{ secrets.GH_DOCKER_USER }}/server:backend
          docker login -u ${{ secrets.GH_DOCKER_USER }} -p ${{ secrets.GH_DOCKER_PASSWORD }}
          docker push ${{ secrets.GH_DOCKER_USER }}/server:backend

      # - name: Trigger deployment backend
      #   run: |
      #     curl -X POST https://api.render.com/deploy/srv-cosbmei0si5c739sn7v0?key=jQmb2AseMfw
